package cli

import (
	"flag"
	"fmt"
	"io"

	"github.com/ghantakiran/OTEL/contract"
	"github.com/ghantakiran/OTEL/controlplane"
	"github.com/ghantakiran/OTEL/guardrail"
)

const compileUsage = `usage: otel-guardrail compile [--profiles <profiles.yaml>] <telemetry-contract.yaml>

Compiles a Telemetry Contract with its Service Tier's Pipeline Profile into
collector configuration for that service's Agent, and writes it to stdout.

The Contract says what the service emits, the Service Tier Taxonomy says what its
tier must emit, and the Profile says how it ships. A Contract that omits a Signal
its tier mandates, names something that is not a Signal, or belongs to a tier with
no published Profile does not compile.

This does not run Guardrails. Use 'otel-guardrail check' for that: compiling tells
you what would ship, checking tells you whether it is allowed to.

  --profiles  Pipeline Profiles to compile against. Defaults to the org Profiles
              built into this binary (controlplane/profiles.yaml).

Exit codes: 0 compiled, 1 the Contract cannot be compiled, 2 the compiler could
not run.`

func runCompile(args []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("compile", flag.ContinueOnError)
	flags.SetOutput(stderr)
	flags.Usage = func() { fmt.Fprintln(stderr, compileUsage) }
	profilePath := flags.String("profiles", "", "Pipeline Profiles to compile against (default: the Profiles built into this binary)")
	if err := flags.Parse(args); err != nil {
		return exitError
	}
	if flags.NArg() != 1 {
		fmt.Fprintln(stderr, compileUsage)
		return exitError
	}

	// A missing or malformed input file is the platform team's problem, not a
	// statement about the service — exit 2, the same split `check` makes.
	declared, err := contract.Load(flags.Arg(0))
	if err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: %v\n", err)
		return exitError
	}
	taxonomy, err := guardrail.CentralTaxonomy()
	if err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: %v\n", err)
		return exitError
	}
	profiles, err := pipelineProfilesFrom(*profilePath)
	if err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: %v\n", err)
		return exitError
	}

	// Whereas a Contract that cannot be compiled is a finding about that Contract,
	// and the service team is who fixes it: exit 1.
	config, err := controlplane.Compile(declared, taxonomy, profiles)
	if err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: %v\n", err)
		return exitViolation
	}
	if err := config.Validate(); err != nil {
		// A compiled config that is not coherent is a bug in the compiler or the
		// Profiles, never in the Contract.
		fmt.Fprintf(stderr, "otel-guardrail: the compiled config is not coherent: %v\n", err)
		return exitError
	}

	rendered, err := config.YAML()
	if err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: %v\n", err)
		return exitError
	}
	fmt.Fprintf(stdout, "# Compiled from %s for Service Tier %s.\n", flags.Arg(0), declared.Tier)
	fmt.Fprint(stdout, "# Generated by otel-guardrail compile — do not edit; change the Contract or the Profile.\n")
	stdout.Write(rendered)
	return exitOK
}

// pipelineProfilesFrom picks the Profiles to compile against: the ones the caller
// pointed at, else the org Profiles compiled into this binary.
func pipelineProfilesFrom(path string) (*controlplane.ProfileSet, error) {
	if path == "" {
		return controlplane.CentralProfiles()
	}
	return controlplane.LoadProfiles(path)
}
