package cli

import (
	"flag"
	"fmt"
	"io"

	"github.com/ghantakiran/OTEL/controlplane"
)

const gatewayUsage = `usage: otel-guardrail gateway [--declaration <gateway.yaml>] [--profiles <profiles.yaml>]

Compiles the org's Gateway Declaration into collector configuration for the shared
Gateway, and writes it to stdout.

The Gateway receives OTLP from every Agent in the fleet, rebatches across all of
them, and exports to a Backend. It takes no Telemetry Contract: there is one
Gateway, shared, and nothing about it is per service or per tier — which is why its
shape is declared once in controlplane/gateway.yaml rather than in a Pipeline
Profile.

The Pipeline Profiles are read too, and cross-checked: every Profile forwards its
tier's Agents to an address, and the Gateway must be the thing answering there. A
Gateway that listens somewhere no Agent is sending does not compile.

  --declaration  Gateway Declaration to compile. Defaults to the org declaration
                 built into this binary (controlplane/gateway.yaml).
  --profiles     Pipeline Profiles to cross-check against. Defaults to the org
                 Profiles built into this binary (controlplane/profiles.yaml).

Exit codes: 0 compiled, 1 the Gateway cannot be compiled as declared, 2 the
compiler could not run.`

func runGateway(args []string, stdout, stderr io.Writer) int {
	flags := flag.NewFlagSet("gateway", flag.ContinueOnError)
	flags.SetOutput(stderr)
	flags.Usage = func() { fmt.Fprintln(stderr, gatewayUsage) }
	declarationPath := flags.String("declaration", "", "Gateway Declaration to compile (default: the declaration built into this binary)")
	profilePath := flags.String("profiles", "", "Pipeline Profiles to cross-check against (default: the Profiles built into this binary)")
	if err := flags.Parse(args); err != nil {
		return exitError
	}
	if flags.NArg() != 0 {
		// Unlike `compile`, this takes no file argument: there is one Gateway, and a
		// stray path here means the caller expected a per-service Gateway.
		fmt.Fprintln(stderr, gatewayUsage)
		return exitError
	}

	// A file that is missing, unparseable, or not a Gateway Declaration at all means
	// the compiler had no input — exit 2, the same split `compile` makes.
	declaration, err := gatewayDeclarationFrom(*declarationPath)
	if err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: %v\n", err)
		return exitError
	}
	profiles, err := pipelineProfilesFrom(*profilePath)
	if err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: %v\n", err)
		return exitError
	}

	// Whereas a declaration that describes a Gateway this cannot build is a finding
	// about that declaration, and whoever wrote it is who fixes it: exit 1.
	config, err := controlplane.CompileGateway(declaration, profiles)
	if err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: %v\n", err)
		return exitViolation
	}
	if err := config.Validate(); err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: the compiled Gateway config is not coherent: %v\n", err)
		return exitError
	}

	rendered, err := config.YAML()
	if err != nil {
		fmt.Fprintf(stderr, "otel-guardrail: %v\n", err)
		return exitError
	}
	fmt.Fprintf(stdout, "# Compiled for the shared Gateway, which answers on %s.\n", declaration.Address)
	fmt.Fprint(stdout, "# Generated by otel-guardrail gateway — do not edit; change the Gateway Declaration.\n")
	stdout.Write(rendered)
	return exitOK
}

// gatewayDeclarationFrom picks the declaration to compile: the one the caller
// pointed at, else the org declaration compiled into this binary.
func gatewayDeclarationFrom(path string) (*controlplane.GatewayDeclaration, error) {
	if path == "" {
		return controlplane.CentralGateway()
	}
	return controlplane.LoadGateway(path)
}
